plugins {
    id 'java'

    id("com.gradleup.shadow") version "9.0.0-rc1"
}

group = 'org.alextheracer1'
version = '1.0'

tasks.shadowJar {
    archiveBaseName.set("LCD-Music-Java-Server")
    archiveVersion.set("1.0.0")
    archiveClassifier.set("all") // Optional

    manifest {
        attributes["Main-Class"] = "org.alextheracer1.Main" // Set the main class here
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    implementation 'com.google.code.gson:gson:2.8.9'
    testImplementation 'org.junit.jupiter:junit-jupiter'
   // implementation 'com.github.hypfvieh:dbus-java:3.2.1'

    implementation 'io.github.java-native:jssc:2.10.2'

    // Log4j API + Core
    implementation 'org.apache.logging.log4j:log4j-api:2.24.1'
    implementation 'org.apache.logging.log4j:log4j-core:2.24.1'

    // Bridge SLF4J to Log4j2
    implementation 'org.apache.logging.log4j:log4j-slf4j2-impl:2.24.1'

    implementation 'org.slf4j:slf4j-api:2.0.17'
}

test {
    useJUnitPlatform()
}